name: Build Rust WASM and Deploy to Pages

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Sử dụng rustup có sẵn trên máy ảo GitHub (Không cần Action bên thứ 3)
      - name: Cài đặt Rust target
        run: |
          rustup default stable
          rustup target add wasm32-unknown-unknown

      - name: Cài đặt wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Biên dịch Rust sang WASM
        run: wasm-pack build --target web

      - name: Chuẩn bị thư mục Deploy
        run: |
          mkdir deploy_folder
          cp index.html deploy_folder/
          cp -r pkg deploy_folder/

      # 100% Action do GitHub trực tiếp tạo và quản lý (actions/*)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './deploy_folder'

      - name: Deploy lên GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
